name: fwupd
version-script: cat $SNAPCRAFT_STAGE/version
version: 'daily'
summary: fwupd
description: |
  fwupd.

grade: devel
confinement: classic

apps:
  fwupdtool:
    command: fwupdtool.wrapper
    completer:
      usr/share/bash-completion/completions/fwupdtool

parts:
  libefivar-dev:
    plugin: make
    source: https://github.com/rhboot/efivar.git
    source-type: git
    build-packages:
      - libpopt-dev
    organize:
      usr/lib64: usr/lib/x86_64-linux-gnu
  libfwup-dev:
    plugin: make
    source: https://github.com/rhboot/fwupdate.git
    source-type: git
    make-parameters:
      - EFIDIR=ubuntu
      - GNUEFIDIR=/usr/lib
      - LIBDIR=$SNAPCRAFT_STAGE/usr/lib/x86_64-linux-gnu
      - libdir=/usr/lib/x86_64-linux-gnu
      - PKG_CONFIG_PATH=$SNAPCRAFT_STAGE/usr/lib/x86_64-linux-gnu/pkgconfig
      - --eval=export PKG_CONFIG_PATH
    build-packages:
      - elfutils
      - gnu-efi
      - libasm1
      - libdw1
      - libefivar-dev
      - libsmbios-dev
      - libsmbios2v5
    after: [libefivar-dev]
  appstream-glib-dev:
    plugin: meson
    meson-parameters: [--prefix=/usr, -Dgtkdoc=false]
    source: https://github.com/hughsie/appstream-glib
    source-type: git
    build-packages:
      - intltool
      - libarchive-dev
      - libgcab-dev
      - libgdk-pixbuf2.0-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libjson-glib-dev
      - libsoup2.4-dev
      - libsqlite3-dev
      - libyaml-dev
      - uuid-dev
      - xmlto
    after: [libfwup-dev]
  fwupd:
    plugin: meson
    meson-parameters: [--prefix=/usr, --libexecdir=/usr/lib, -Dgtkdoc=false, -Dsnap=true]
    source: https://github.com/hughsie/fwupd
    source-branch: wip/superm1/noinst
    source-type: git
    override-build: |
      snapcraftctl build
      echo $(git describe HEAD) > $SNAPCRAFT_STAGE/version
    build-packages:
      - fontconfig
      - fonts-dejavu
      - gcab
      - gettext
      - gir1.2-pango-1.0
      - gnutls-bin
      - gnutls-dev
      - gobject-introspection
      - gtk-doc-tools
      - help2man
      - libappstream-glib-dev
      - libarchive-dev
      - libcairo-dev
      - libcairo-gobject2
      - libcolord-dev
      - libcolorhug-dev
      - libefivar-dev
      - libelf-dev
      - libfreetype6-dev
      - libfwup-dev
      - libgcab-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgpgme11-dev
      - libgudev-1.0-dev
      - libgusb-dev
      - libjson-glib-dev
      - libpolkit-gobject-1-dev
      - libsmbios-dev
      - libsoup2.4-dev
      - libsqlite3-dev
      - libtool-bin
      - locales
      - meson
      - pkg-config
      - policykit-1
      - python3-gi-cairo
      - python3-pil
      - python3-requests
      - systemd
      - udev
      - umockdev
      - valac
    stage-packages:
      - libusb-1.0-0
      - libappstream-glib8
      - libarchive13
      - libc6
      - libefiboot1
      - libgusb2
      - libsmbios-c2
      - libfwup1
      - libgpgme11
      - libelf1
      - libcolorhug2
      - libgudev-1.0-0
      - libjson-glib-1.0-0
      - liblzma5
    prime:
      - -usr/bin
      - -usr/sbin
      - -usr/lib/gnupg
      - -usr/share/mime
      - -usr/share/man
      - -usr/share/GConf
      - -etc/X11
      - -etc/ldap
      - -etc/logcheck
      - -usr/lib/dconf
      - -usr/lib/gcc
      - -usr/lib/glib-networking
      - -usr/lib/gnupg2
      - -usr/lib/sasl2
      - -usr/lib/systemd
      - -usr/lib/*/audit
      - -usr/share/glib-2.0/schemas
      - -usr/share/X11
      - -usr/include
      - -etc/dbus-1
      - -lib/systemd
      - -lib/udev
      - -usr/lib/fwupd/fwupd
      - -usr/share/dbus-1
      - -usr/share/gnupg
      - -usr/share/lintian
      - -usr/share/pkgconfig
      - -usr/share/installed-tests
      - -usr/share/polkit-1
      - -usr/share/vala
      - -usr/share/doc
  fwupdtool-wrapper:
    plugin: dump
    source: .
    stage:
    - fwupdtool.wrapper
